const counterConfigs = [
  { uid: 'tr001', label: '도플라밍고',    type: '물딜', grade: '초월' },
  { uid: 'tr002', label: '로빈',          type: '물딜', grade: '초월' },
  { uid: 'tr003', label: '보니',          type: '물딜', grade: '초월' },
  { uid: 'tr004', label: '료쿠규',        type: '물딜', grade: '초월' },
  { uid: 'tr005', label: '루피',          type: '물딜', grade: '초월' },
  { uid: 'tr006', label: '바질호킨스',    type: '물딜', grade: '초월' },
  { uid: 'tr007', label: '사보',          type: '물딜', grade: '초월' },
  { uid: 'tr008', label: '야마토',        type: '물딜', grade: '초월' },
  { uid: 'tr009', label: '우솝',          type: '물딜', grade: '초월' },
  { uid: 'tr010', label: '조로',          type: '물딜', grade: '초월' },
  { uid: 'tr011', label: '징베',          type: '물딜', grade: '초월' },
  { uid: 'tr012', label: '쵸파',          type: '물딜', grade: '초월' },
  { uid: 'tr013', label: '후지토라',      type: '물딜', grade: '초월' },
  { uid: 'tr101', label: '검은수염',      type: '마딜', grade: '초월' },
  { uid: 'tr102', label: '나미',          type: '마딜', grade: '초월' },
  { uid: 'tr103', label: '로우',          type: '마딜', grade: '초월' },
  { uid: 'tr104', label: '루치',          type: '마딜', grade: '초월' },
  { uid: 'tr105', label: '루피 기어포스', type: '마딜', grade: '초월' },
  { uid: 'tr106', label: '브룩',          type: '마딜', grade: '초월' },
  { uid: 'tr107', label: '상디',          type: '마딜', grade: '초월' },
  { uid: 'tr108', label: '샹크스',        type: '마딜', grade: '초월' },
  { uid: 'tr109', label: '시라호시',      type: '마딜', grade: '초월' },
  { uid: 'tr110', label: '아오키지',      type: '마딜', grade: '초월' },
  { uid: 'tr111', label: '아카이누',      type: '마딜', grade: '초월' },
  { uid: 'tr112', label: '타시기',        type: '마딜', grade: '초월' },
  { uid: 'tr113', label: '키드',          type: '마딜', grade: '초월' },
  { uid: 'tr114', label: '키자루',        type: '마딜', grade: '초월' },
  { uid: 'tr115', label: '프랑키',        type: '마딜', grade: '초월' },
];

window.counterConfigs = counterConfigs;